import fs from 'node:fs';
const fail=m=>{console.error('FAIL · '+m);process.exit(1)}; const ok=m=>console.log('PASS · '+m);
const must=(c,m)=>c?ok(m):fail(m);
const required=['site/index.html','site/experience-atlas.html','site/assets/site-nav.css','site/assets/site-nav.js','site/assets/experience-atlas.css','site/assets/experience-atlas.js','data/site-experience-atlas.json','schemas/site-experience-atlas.schema.json','docs/SITE_EXPERIENCE_ATLAS_V37.md'];
for(const f of required) must(fs.existsSync(f),`required file exists: ${f}`);
const home=fs.readFileSync('site/index.html','utf8'), atlas=fs.readFileSync('site/experience-atlas.html','utf8'), nav=fs.readFileSync('site/assets/site-nav.js','utf8'), navcss=fs.readFileSync('site/assets/site-nav.css','utf8'), app=fs.readFileSync('site/assets/experience-atlas.js','utf8');
must(/Experience Atlas/.test(home+atlas),'home and atlas expose Experience Atlas');
must(/Find the right proof surface/.test(nav),'global menu has clear intent copy');
must(/GoalOS AGIJobManager/.test(nav),'global nav brand is present');
must(/g-nav-enabled/.test(navcss),'global nav hides old crowded nav safely');
must(/Proof-Settlement Lifecycle/.test(nav) && /Evidence Docket Composer/.test(nav) && /Trust Equation Simulator/.test(nav),'newer v34-v36 pages are included in global nav');
must(/AGIALPHA Boundary/.test(nav) && /Privacy/.test(nav) && /Legal Boundary/.test(nav),'boundary pages are included in global nav');
must(/Start|Proof loop|Selection|Compounding|System control|Settlement|Evidence|Operate|Boundary/.test(nav),'intent categories are represented');
for(const bad of ['localStorage','sessionStorage','document.cookie','eth_requestAccounts','wallet_switchEthereumChain','eth_sendTransaction','<form','fetch(\'http','fetch("http']) must(!(nav+app+atlas+home).includes(bad),`forbidden primitive absent: ${bad}`);
const data=JSON.parse(fs.readFileSync('data/site-experience-atlas.json','utf8'));
must(data.routes.length>=35,'atlas data contract includes a complete route library');
must(data.posture.noUserDataWanted===true && data.posture.noWalletOnPublicPages===true,'atlas data contract encodes public-safe posture');
for(const href of ['experience-atlas.html','proof-settlement-lifecycle.html','trust-equation-simulator.html','evidence-docket-composer.html','until-done-mission-control.html','proof-conditioned-router-observatory.html']) must(nav.includes(href) && atlas.includes(href) || app.includes(href),`route present in navigation/atlas: ${href}`);
console.log('Site Experience Atlas v37 PASS');
