import {readFileSync,existsSync,writeFileSync} from 'node:fs';
const files=['site/index.html','site/operator-console.html','site/evidence/index.html','site/architecture.html','site/verification.html','site/assets/atelier.css','site/assets/atelier.js','site/production-url.json','site/build-manifest.json','data/canonical-identities.json','schemas/goalos-intent.schema.json','schemas/evidence-docket.schema.json'];
const results=[]; const pass=(name,ok,msg='')=>{results.push({name,ok,msg}); if(!ok) throw new Error(`${name}: ${msg}`)};
for(const f of files) pass(`exists ${f}`,existsSync(f),'missing file');
const all=files.filter(f=>f.endsWith('.html')||f.endsWith('.json')||f.endsWith('.js')).map(f=>readFileSync(f,'utf8')).join('\n');
const required=['0xB3AAeb69b630f0299791679c063d68d6687481d1','0xa61a3b3a130a9c20768eebf97e21515a6046a1fa','https://montrealai.github.io/goalos-agijobmanager-ascension/','No wallet auto-connect','No token approval','No transaction broadcast','Evidence Docket 6.1','read-only'];
for(const s of required) pass(`contains ${s.slice(0,34)}`,all.includes(s),`missing ${s}`);
const forbidden=['eth_requestAccounts','eth_sendTransaction','wallet_switchEthereumChain','personal_sign','setApprovalForAll','privateKey =','new ethers.Wallet','window.ethereum.request'];
for(const s of forbidden) pass(`forbidden ${s}`,!all.includes(s),'unsafe primitive present');
const manifest=JSON.parse(readFileSync('site/production-url.json','utf8'));
pass('production URL exact',manifest.productionUrl==='https://montrealai.github.io/goalos-agijobmanager-ascension/',manifest.productionUrl);
pass('contract exact',manifest.contract==='0xB3AAeb69b630f0299791679c063d68d6687481d1',manifest.contract);
pass('token exact',manifest.token==='0xa61a3b3a130a9c20768eebf97e21515a6046a1fa',manifest.token);
const md=['# AGIJobManager Ascension QA','',`Generated: ${new Date().toISOString()}`,'','Status: PASS','',...results.map(r=>`- ${r.ok?'PASS':'FAIL'}: ${r.name}`),''].join('\n');
writeFileSync('AGIJOBMANAGER_ASCENSION_QA.md',md);
console.log(`GoalOS AGIJobManager Ascension QA PASS (${results.length}/${results.length})`);
