import fs from 'node:fs';
const ok=(c,m)=>{if(!c){console.error('FAIL · '+m);process.exit(1)}console.log('PASS · '+m)};
const files=['site/command-center.html','site/assets/navigation-v37.css','site/assets/navigation-v37.js','data/site-navigation-v37.json','schemas/site-navigation-v37.schema.json','docs/WEBSITE_COMMAND_CENTER_V37.md'];
for(const f of files) ok(fs.existsSync(f),`required v37 file exists: ${f}`);
const html=fs.readFileSync('site/command-center.html','utf8');
const js=fs.readFileSync('site/assets/navigation-v37.js','utf8');
const css=fs.readFileSync('site/assets/navigation-v37.css','utf8');
const data=JSON.parse(fs.readFileSync('data/site-navigation-v37.json','utf8'));
ok(/Command Center/.test(html),'Command Center page is named clearly');
ok(data.pages.length>=30,'navigation atlas covers at least 30 public routes');
ok(data.groups.length>=7,'navigation atlas is grouped');
ok(data.journeys.length>=5,'guided journeys are present');
ok(data.pages.some(p=>p.href==='trust-equation-simulator.html'),'Trust Equation is included');
ok(data.pages.some(p=>p.href==='proof-settlement-lifecycle.html'),'Proof-Settlement Lifecycle is included');
ok(data.pages.some(p=>p.href==='evidence-docket-composer.html'),'Evidence Docket Composer is included');
ok(data.pages.some(p=>p.href==='legal.html')&&data.pages.some(p=>p.href==='agialpha-token-boundary.html'),'legal and token boundaries are included');
ok(/NavigationReceipt/.test(js),'NavigationReceipt export exists');
ok(/nav37-drawer/.test(css)&&/cc-cardgrid/.test(css),'drawer and atlas UI styles exist');
ok(!/localStorage|sessionStorage|document\.cookie|fetch\(['"]https?:|ethereum\.request|eth_requestAccounts|wallet_switchEthereumChain/i.test(html+js),'v37 page avoids storage, cookies, external fetch, wallet calls, and network primitives');
console.log('Website Command Center v37 PASS');
